prostages/src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomCourt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $siteWeb;

    /**
     * @ORM\ManyToMany(targetEntity=Stage::class, inversedBy="formations")
     */
    private $stage;

    public function __construct()
    {
        $this->stage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getNomCourt(): ?string
    {
        return $this->nomCourt;
    }

    public function setNomCourt(?string $nomCourt): self
    {
        $this->nomCourt = $nomCourt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->siteWeb;
    }

    public function setSiteWeb(string $siteWeb): self
    {
        $this->siteWeb = $siteWeb;

        return $this;
    }

    /**
     * @return Collection|Stage[]
     */
    public function getStage(): Collection
    {
        return $this->stage;
    }

    public function addStage(Stage $stage): self
    {
        if (!$this->stage->contains($stage)) {
            $this->stage[] = $stage;
        }

        return $this;
    }

    public function removeStage(Stage $stage): self
    {
        $this->stage->removeElement($stage);

        return $this;
    }
}

prostages/src/Controller/Tp1Controller.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\StageRepository;
use App\Entity\Stage;

class Tp1Controller extends AbstractController
{
    /**
     * @Route("/", name="tp1")
     */
    public function index(): Response
    {
        $repositoryStages = $this->getDoctrine()->getRepository(Stage::class);
        $listeStage = $repositoryStages->findAll();

        return $this->render('tp1/index.html.twig', [
            'listeStage' => $listeStage
        ]);
    }
 }
?>

prostages/templates/tp1/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    Liste des stages
    <table class="table">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Nom</th>
        <th scope="col">Titre</th>
        <th scope="col">Activité</th>
        <th scope="col">Adresse mail</th>
        <th scope="col">Formations</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {# {% for stage in listeStage %}
            <tr>
            <th scope="row">{{stage.id}}</th>
            <td>{{stage.titre}}</td>
            <td>{{stage.nom}}</td>
            <td>{{stage.detail}}</td>
            <td>{{stage.email}}</td>
            <td>{{stage.entreprise}}</td>
            <td>{{stage.formations}}</td>
            <td> <a class="nav-link" href="/stages/1">Consulter</a></td>
            </tr>
        {% endfor %} #}
    </tbody>
    </table>
</div>
{% endblock %}